---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.linux.amd64
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    auto_tag: true
    auto_tag_suffix: linux-amd64
  when:
    branch:
    - master
    event:
    - push
    - tag

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: publish
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.linux.arm64
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    auto_tag: true
    auto_tag_suffix: linux-arm64
  when:
    branch:
    - master
    event:
    - push
    - tag

---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: publish
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.linux.arm
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    auto_tag: true
    auto_tag_suffix: linux-arm
  when:
    branch:
    - master
    event:
    - push
    - tag

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: fouts/salt-master:latest
    template: fouts/salt-master:OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64
  when:
    branch:
    - master
    event:
    - push

depends_on:
  - linux-arm
  - linux-amd64
  - linux-arm64

...
