---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: false
    dockerfile: docker/Dockerfile.linux.amd64
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    tags:
      - '2019.2.0-amd64'
  when:
    event:
    - tag

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: false
    dockerfile: docker/Dockerfile.linux.arm64
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    tags:
      - '2019.2.0-arm64'
  when:
    event:
    - tag

---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: false
    dockerfile: docker/Dockerfile.linux.arm
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    tags:
      - '2019.2.0-arm'
  when:
    event:
    - tag

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: server
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username
  when:
    event:
    - tag
depends_on:
  - linux-arm
  - linux-amd64
  - linux-arm64

...

