kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
  publish_saltmaster_armv8:
    image: plugins/docker
    repo: fouts/salt-master
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    auto_tag_suffix: linux-arm64
    auto_tag: true
    when:
      branch: master
      event: push
      platform: linux/arm64

platform:
  os: linux
  arch: arm
  
steps:
  publish_saltmaster_armv7:
    image: plugins/docker
    repo: fouts/salt-master
    dockerfile: Dockerfile.arm
    secrets: [ docker_username, docker_password ]
    auto_tag_suffix: linux-arm
    auto_tag: true
    when:
      branch: master
      event: push
      platform: linux/arm

platform:
  os: linux
  arch: amd64

steps:
  publish_saltmaster_x86_64:
    image: plugins/docker
    repo: fouts/salt-master
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    auto_tag_suffix: linux-amd64
    auto_tag: true
    when:
      branch: master
      event: push
      platform: linux/amd64

